OnlyFlans-1/onlyflans/onlyflans/urls.py
#Rutas generales del proyecto OnlyFlans
from django.contrib import admin
from django.urls import path, include
from web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    # Flanes
    path('flan/', views.flan_list, name='flan_list'),
    # Welcome
    path('welcome/', views.welcome, name='welcome'),
    path('registration/new_client/welcome', views.welcome, name='welcome'),
    path('accounts/login/?next=/registration/new_client/welcome', views.welcome, name='welcome'),
    #Formulario de contacto
    path('contact/', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    #Registro de clientes
    path('registration/', views.registration_view, name='registration_view'),
    path('registration/', views.registration_view, name='registration_form'),
    path('registration/new_client/', views.new_client, name='new_client'),
    #Clientes
    path('client/', views.Client, name='client'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.login, name='login'),
    path('logout/', views.user_login, name='logout'),
]



OnlyFlans-1/onlyflans/web/urls.py
#Rutas específicas de la aplicación
from django.urls import path
from . import views
from .views import registration_view, login
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    path('welcome/', views.welcome, name='welcome'),
    path('login/', login, name='login'),
    path('logout/', views.user_login, name='logout'),
    path('client/', views.Client, name='client'),
    path('register/', views.registration_view, name='registration'),
    path('new_client/', views.new_client, name='new_client'),
]

OnlyFlans-1/onlyflans/web/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import Client

class ContactFormForm(forms.Form):
    customer_email = forms.EmailField(label='Email')
    customer_name = forms.CharField(max_length=64, label='Name')
    message = forms.CharField(label='Message')

class LoginForm(forms.Form):
    username = forms.CharField(max_length=64, label="Nombre")
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class ClientFormForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'lastname', 'email', 'age', 'birth_date', 'address', 'password']
        widgets = {
            'password': forms.PasswordInput(),  # Para ocultar el campo de contraseña
        }

OnlyFlans-1/onlyflans/web/templates/about.html
<!doctype html>
{%load static%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Acerca de OnlyFlans</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>

    {%block 'navbar'%}
    {%include 'navbar.html' %}
    {% endblock %}

    <div class="container">
        <img src="{% static 'img/OnlyFlans.png'%}" alt="logo" width="18%">
        <h1 class="fw-bold text-primary">¿Quiénes somos?</h1>
    <div>

    {%block 'carrousel' %}
    {%include 'carrousel.html' %}
    {% endblock %}


    {%block 'suscribe'%}
    {%include 'suscribe.html'%}
    {% endblock %}
    

    {%block 'footer'%}
    {%include 'footer.html'%}
    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

OnlyFlans-1/onlyflans/web/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Suscripción a OnlyFlans</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    
</head>
<body>

{% block navbar %}
{% if show_navbar %}
{% endif %}
{% endblock %}

<div class="container background-opacity my-3">
    {% block content %}{% endblock %}
    {% block carrousel %}
{% if show_carrousel %}
{% endif %}
{% endblock %}
</div>

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<!--Funcinamiento del modal de login-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

</body>
</html>


OnlyFlans-1/onlyflans/web/templates/carrousel.html
{% load static %}
<div class="container-fluid px-0">
    <div class="row">
        <div class="col-lg-6 py-5">
            <div class="container">
                <h2 class="fw-bold mb-4">El Secreto de un Buen Postre</h2>
                <p class="fs-5">OnlyFlans es una empresa dedicada a la producción y venta de pasteles y postres gourmet de alta calidad. Fundada en 2021, nuestra misión es ofrecer a nuestros clientes la experiencia de disfrutar de un postre clásico con un toque moderno y artesanal. Utilizamos ingredientes frescos y naturales, sin conservantes ni colorantes artificiales, para garantizar que cada bocado tenga un sabor auténtico y delicioso.</p>
            </div>
        </div>
        <div class="col-lg-6">
            <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img/flanNaranja.jpg'%}" class="d-block w-100" alt="flanNaranjaCarrusel">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/carrusel2.jpg'%}" class="d-block w-100" alt="flanCarameloCarrusel">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/carrusel4.jpg'%}" class="d-block w-100" alt="flanVainillaBerries">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>

OnlyFlans-1/onlyflans/web/templates/contact.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<img src="{% static 'img/OnlyFlans.png' %}" alt="logo" width="25%">
<div class="row">
    <div class="col-12 col-md-8 m-auto p-5">
        <h3 class="text-primary">¡Escríbenos!</h3>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="border rounded p-4 shadow-lg">
            <form action="{% url 'contact' %}" method="post">
                <input type="hidden" name="csrfmiddlewaretoken" value="a8j8yKmBhRUeud2TWMf4v3ISNczsfPsbtzwFg28XlhDF3B8w9hxhyELCEOpwRnKt">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control rounded-pill" id="id_customer_email" name="customer_email" placeholder="name@example.com">
                </div>
                <div class="mb-3">
                    <label for="id_customer_name" class="form-label">Nombre</label>
                    <input type="text" class="form-control rounded-pill" id="id_customer_name" name="customer_name" placeholder="Ingresa tu nombre">
                </div>
                <div class="mb-3">
                    <label for="id_message" class="form-label">Mensaje</label>
                    <textarea class="form-control rounded-pill" id="id_message" name="message" rows="3"></textarea>
                </div> 
                <input type="Submit" class="btn btn-success btn-lg rounded-pill" value="Enviar">
            </form>
        </div>
    </div>
</div>
{% endblock %}

OnlyFlans-1/onlyflans/web/templates/flan.html
{% block content %}
<div class="row">
    <div class="col-12 d-flex flex-column text-center">
        <div class="background-opacity my-3 py-3">
            <h1>{{ flan.nombre }}</h1>
            <p class="fs-5">{{ flan.description }}</p>
        </div>
        <div class="my-4">
            <img class="border-flan" src="{{ flan.img_url }}" alt="" width="500px" height="400px">
        </div>
        <div class="background-opacity my-3">
            <h3>Ingredientes</h3>
            <pre>{{ flan.ingredients }}</pre>
        </div>
        <div class="offset-2 col-8 my-3">
            <h3>Preparación</h3>
            <p class="formated-text px-5">{{ flan.preparation }}</p>
        </div>
        <!-- Nuevas líneas para mostrar la fecha y hora de creación y modificación -->
        <div class="background-opacity my-3">
            <p>Fecha de creación: {{ flan.created_at }}</p>
            <p>Fecha de modificación: {{ flan.modified_at }}</p>
        </div>
    </div>
</div>
{% endblock %}

OnlyFlans-1/onlyflans/web/templates/footer.html
{% load static %}
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-2 my-2 border-top w-100">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <img src="{% static 'img/OnlyFlans.png' %}" width="75"><use xlink:href="home"></use></img>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">2024 Creado por Valeria Fariña, para Desafío Latam</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
    </footer>
</div>

OnlyFlans-1/onlyflans/web/templates/header.html
    {%load static%}
    <!--<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <img src="{% static 'img/OnlyFlans.png'%}" alt="logo" width="65">
        </a>

        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        <li>
            <a href="/" class="nav-link text-secondary">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"></use></svg>
            Home
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
            Catálogo
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"></use></svg>
            Usuarios
            </a>
        </li>
        </ul>
    </div>-->

OnlyFlans-1/onlyflans/web/templates/hero.html
{% load static %}
<div class="container col-xxl-8 px-4 py-2">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-2">
        <div class="col-lg-6">
            <h1 class="display-6 fw-bold fs-1 text-body-emphasis lh-1 mb-3">El Secreto de un Buen Postre</h1>
            <p class="lead">OnlyFlans es una empresa dedicada a la producción y venta de pasteles y postres gourmet de alta calidad. Fundada en 2021, nuestra misión es ofrecer a nuestros clientes la experiencia de disfrutar de un postre clásico con un toque moderno y artesanal. Utilizamos ingredientes frescos y naturales, sin conservantes ni colorantes artificiales, para garantizar que cada bocado tenga un sabor auténtico y delicioso.</p>
        </div>
        <div class="col-10 col-sm-8 col-lg-6">
            <img src="{% static 'img/flan-navidad.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
        </div>
    </div>
</div>

OnlyFlans-1/onlyflans/web/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
<!--Header-->
{%block 'header'%}
{%include 'header.html'%}
{% endblock %}

<!--Navbar-->
{%block 'navbar'%}
{%include 'navbar.html'%}
{% endblock %}

<div class="container">
    <h1 class="mt-5">Flanes Públicos</h1>
    <div class="row">
        {% for flan in lista_flanes %}
        <div class="col-sm-3 mb-3">
            <div class="card h-100">
                <img class="card-img-top" src="{{ flan.img_url }}" alt="{{ flan.name }}" style="object-fit: cover; height: 200px;">
                <div class="card-body">
                    <h5 class="card-title">{{ flan.name }}</h5>
                    <p class="card-text">{{ flan.description }}</p>
                </div>
                <div class="card-footer d-flex justify-content-center">
                    <a href="#" class="btn btn-primary">
                        <img src="{% static 'img/carrito.png' %}" alt="carrito" width="20" height="20">
                        Agregar a carrito
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
        

{%block 'suscribe'%}
{%include 'suscribe.html' %}
{% endblock %}

<!--Footer-->
{%block 'footer'%}
{%include 'footer.html'%}
{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

OnlyFlans-1/onlyflans/web/templates/login.html
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Iniciar Sesión</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo Electrónico</label>
                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Contraseña</label>
                        <input type="password" class="form-control" id="password" required>
                    </div>
                    <div class="d-grid">
                        <a href="{% url 'welcome' %}"></a>
                        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

OnlyFlans-1/onlyflans/web/templates/navbar.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <!-- Logo con enlace a la página de inicio -->
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'img/OnlyFlans.png' %}" alt="logo" width="15%">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <!-- Toolbar con grupos de botones -->
                <div class="btn-toolbar justify-content-end" role="toolbar" aria-label="Toolbar with button groups">
                    <!-- Primer grupo de botones -->
                    <div class="btn-group me-2" role="group" aria-label="First group">
                        <a class="btn btn-primary" href="{% url 'welcome' %}">Welcome</a>
                        <a class="btn btn-primary" href="{% url 'about' %}">About</a>
                    </div>
                    <!-- Segundo grupo de botones -->
                    <div class="btn-group me-2" role="group" aria-label="Second group">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loginModal">Login</button>
                        <a class="btn btn-secondary" href="{% url 'logout' %}">Logout</a>
                    </div>
                    <!-- Tercer grupo de botones -->
                    <div class="btn-group" role="group" aria-label="Third group">
                        <a href="/admin/login/?next=/admin/" class="btn btn-info">Admin</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Iniciar Sesión</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo Electrónico</label>
                        <input type="email" class="form-control" id="email" name="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

OnlyFlans-1/onlyflans/web/templates/registration_form.html
{% extends 'base.html' %}
{% block content %}
{% block title %}
{% load static %}
<div class="col-md-4">
    <a href="{% url 'index' %}">
        <img src="{% static 'img/OnlyFlans.png' %}" alt="login" width="45%">
    </a>
</div>
{% endblock %}
<div class="row justify-content-center">
    <div class="col-md-7 col-lg-8">
        <div class="card shadow-lg p-4">
            <h4 class="mb-4 text-center">Registro de Cliente</h4>
            <form action="{% url 'registration_view' %}" method="post" >
                {% csrf_token %}
                <div class="row g-3">
                    <div class="col-sm-6">
                        <label for="firstName" class="form-label fs-5">Nombre</label>
                        <input type="text" name="name" class="form-control border border-primary" id="firstName" placeholder="" value="" required />
                        <div class="invalid-feedback">El nombre es requerido.</div>
                    </div>

                    <div class="col-sm-6">
                        <label for="lastName" class="form-label fs-5">Apellido</label>
                        <input type="text" name="lastname" class="form-control border border-primary" id="lastName" placeholder="" value="" required />
                        <div class="invalid-feedback">El apellido es requerido.</div>
                    </div>

                    <div class="col-12">
                        <label for="email" class="form-label fs-5">Correo Electrónico</label>
                        <input type="email" name="email" class="form-control border border-primary" id="email" placeholder="usuario@correo.com" required />
                        <div class="invalid-feedback">Por favor, ingrese un correo electrónico válido.</div>
                    </div>

                    <div class="col-12">
                        <label for="age" class="form-label fs-5">Edad</label>
                        <input type="number" name="age" class="form-control border border-primary" id="age" placeholder="" required />
                        <div class="invalid-feedback">Por favor, ingrese una edad válida.</div>
                    </div>

                    <div class="col-12">
                        <label for="birthDate" class="form-label fs-5">Fecha de cumpleaños</label>
                        <input type="date" name="birth_date" class="form-control border border-primary" id="birthDate" placeholder="Fecha de cumpleaños" required />
                        <div class="invalid-feedback">Por favor, ingrese una fecha de cumpleaños válida.</div>
                    </div>

                    <div class="col-12">
                        <label for="address" class="form-label fs-5">Dirección</label>
                        <input type="text" name="address" class="form-control border border-primary" id="address" placeholder="Dirección" required />
                        <div class="invalid-feedback">La dirección es requerida.</div>
                    </div>

                    <div class="col-12">
                        <label for="password" class="form-label fs-5">Contraseña</label>
                        <input type="password" name="password" class="form-control border border-primary" id="password" placeholder="Contraseña" required minlength="8" />
                        <div class="invalid-feedback">La contraseña debe tener al menos 8 caracteres.</div>
                    </div>

                    <div class="col-12">
                        <label for="confirmPassword" class="form-label fs-5">Confirmar Contraseña</label>
                        <input type="password" class="form-control border border-primary" id="confirmPassword" placeholder="Confirmar Contraseña" required minlength="8" />
                        <div class="invalid-feedback">Las contraseñas deben coincidir y tener al menos 8 caracteres.</div>
                    </div>
                </div>
                <hr class="my-4" />
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="save-info" />
                    <label class="form-check-label fs-5" for="save-info">Guardar esta información para la próxima vez</label>
                </div>

                <div class="col-lg-6 mx-auto">
                    <input type="Submit" class="btn btn-primary btn-lg w-100" value="Enviar">
                </div>
            </form>
        </div>
    </div>
</div>

<br><br>
{% endblock %}
{% block javascript %}
    <script>
        var show_navbar = false;
    </script>
{% endblock %}

OnlyFlans-1/onlyflans/web/templates/suscribe.html
<div class="container">
    <div class="bg-dark text-secondary px-1 py-5 text-center position-relative overflow-hidden" style="width: 100%;">
        <img src="/static/img/flanFrutosVino.jpg" class="position-absolute top-0 start-0 w-100 h-100 object-fit-cover" alt="flanChantilly" loading="lazy" style="opacity: 0.5;">
        <div class="position-relative">
            <h1 class="display-3 fw-bold text-light">Suscríbete</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4 text-light">Nuestros clientes disfrutan de beneficios inigualables, envío gratis, sabores innovadores y regalos especiales durante todo el mes de su cumpleaños.</p>
                <a href="{% url 'registration_view' %}"></a>
                <button type="submit" class="w-100 btn btn-primary btn-lg">Suscribirse</button>
            </div>
        </div>
    </div>
</div>

OnlyFlans-1/onlyflans/web/templates/welcome.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bienvenida/o a Onlyflans</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
    <div class="container">
        <img src="{% static 'img/OnlyFlans.png' %}" alt="logo" width="15%">
        {% if user.is_authenticated %}
        <h3 class="text-primary">¡Bienvenido/a {{ user.get_username }}!</h3>
        {% endif %}
    </div>

    <div class="container">
        <h1 class="mt-5">Flanes Privados</h1>
        <div class="row">
            {% for flan in flan_list %}
            <div class="col-sm-3 mb-3">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ flan.img_url }}" alt="{{ flan.name }}" style="object-fit: cover; height: 200px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ flan.name }}</h5>
                        <p class="card-text">{{ flan.description }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <a href="#" class="btn btn-primary">
                            <img src="{% static 'img/carrito.png' %}" alt="carrito" width="20" height="20">
                            Agregar a carrito
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% for flan in flan_list %}
            <div class="col-sm-3 mb-3">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ flan.img_url }}" alt="{{ flan.name }}" style="object-fit: cover; height: 200px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ flan.name }}</h5>
                        <p class="card-text">{{ flan.description }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <a href="#" class="btn btn-primary">
                            <img src="{% static 'img/carrito.png' %}" alt="carrito" width="20" height="20">
                            Agregar a carrito
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
        {% block footer %}
        {% include 'footer.html' %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>